### PR TITLE
Refactor api explicit availability

### PR DESCRIPTION
**Pull request by davidpomerenke**
Now the `trends` and `impact` endpoint make explicit in their response whether the requested media_source is supported, and specify this in a `limitations` field. (Check out this branch and check the types in the API docs.)

Since the backend and frontend PR environments are not connected at the moment, I think we need to merge this (which breaks the frontend), and then work on the frontend.

### CODE REVIEW

**Comment by vogelino** [comment]
Great! Eventually you could deploy that on a specific api URL (maybe already the case) so that I can make the client compatible with it and then we both merge our branches. This would enable us to work on other branches without breaking things. What do you think?

**Comment by davidpomerenke** [comment]
Sounds good! Or if you like you can also work on this branch, then it's all together. And you can use the URL that you found, yes! 👍

**Comment by davidpomerenke** [comment]
I'll merge this already to avoid some complications with branches (I had some bugfixes mixed into this branch unfortunately). So the frontend will break on dev but that's not an issue right now.

**Comment by vogelino** [comment]
@davidpomerenke you can merge `dev` into your own branch so you don't have to impact the frontend. Now the charts won't load. Is there an API URL representing the state before your modifications, so I can keep working on the rest? Thank you!

**Pull request merged**
